unit IABFunctions.MessageCodes;
// https://interactivebrokers.github.io/tws-api/message_codes.html

interface

{$REGION 'Region uses'}
uses
  Winapi.Windows, System.SysUtils, System.Classes;
{$ENDREGION}

type
  TTypeMessageCodes = (mcSystem, mcWarning, mcClientError, mcTWSError, mcUserError);

  TTWSMessageItem = record
    TypeCode  : TTypeMessageCodes;
    ErrorCode : Integer;
    ErrorMsg  : string;
  end;

const
  ArrayMessages: array[1 .. 310] of TTWSMessageItem = (
    (TypeCode: mcSystem; ErrorCode: 1100; ErrorMsg: 'Connectivity between IB and the TWS has been lost.'),
    (TypeCode: mcSystem; ErrorCode: 1101; ErrorMsg: 'Connectivity between IB and TWS has been restored - data lost.*'),
    (TypeCode: mcSystem; ErrorCode: 1102; ErrorMsg: 'Connectivity between IB and TWS has been restored - data maintained.'),
    (TypeCode: mcSystem; ErrorCode: 1300; ErrorMsg: 'TWS socket port has been reset and this connection is being dropped. Please reconnect on the new port - <port_num>'),
    (TypeCode: mcWarning; ErrorCode: 2100; ErrorMsg: 'New account data requested from TWS. API client has been unsubscribed from account data.'),
    (TypeCode: mcWarning; ErrorCode: 2101; ErrorMsg: 'Unable to subscribe to account as the following clients are subscribed to a different account.'),
    (TypeCode: mcWarning; ErrorCode: 2102; ErrorMsg: 'Unable to modify this order as it is still being processed.'),
    (TypeCode: mcWarning; ErrorCode: 2103; ErrorMsg: 'A market data farm is disconnected.'),
    (TypeCode: mcWarning; ErrorCode: 2104; ErrorMsg: 'Market data farm connection is OK'),
    (TypeCode: mcWarning; ErrorCode: 2105; ErrorMsg: 'A historical data farm is disconnected.'),
    (TypeCode: mcWarning; ErrorCode: 2106; ErrorMsg: 'A historical data farm is connected.'),
    (TypeCode: mcWarning; ErrorCode: 2107; ErrorMsg: 'A historical data farm connection has become inactive but should be available upon demand.'),
    (TypeCode: mcWarning; ErrorCode: 2108; ErrorMsg: 'A market data farm connection has become inactive but should be available upon demand.'),
    (TypeCode: mcWarning; ErrorCode: 2109; ErrorMsg: 'Order Event Warning: Attribute "Outside Regular Trading Hours" is ignored based on the order type and destination. PlaceOrder is now processed.'),
    (TypeCode: mcWarning; ErrorCode: 2110; ErrorMsg: 'Connectivity between TWS and server is broken. It will be restored automatically.'),
    (TypeCode: mcWarning; ErrorCode: 2137; ErrorMsg: 'Cross Side Warning'),
    (TypeCode: mcClientError; ErrorCode: 501; ErrorMsg: 'Already Connected.'),
    (TypeCode: mcClientError; ErrorCode: 502; ErrorMsg: 'Couldn''t connect to TWS. Confirm that "Enable ActiveX and Socket Clients" is enabled and connection port is the same as "Socket Port" on the TWS "Edit->Global Configuration...->API->Settings" menu.'),
    (TypeCode: mcClientError; ErrorCode: 503; ErrorMsg: 'The TWS is out of date and must be upgraded.'),
    (TypeCode: mcClientError; ErrorCode: 504; ErrorMsg: 'Not connected.'),
    (TypeCode: mcClientError; ErrorCode: 10038; ErrorMsg: 'An operation was attempted on something that is not a socket.'),
    (TypeCode: mcTWSError; ErrorCode: 100; ErrorMsg: 'Max rate of messages per second has been exceeded.'),
    (TypeCode: mcTWSError; ErrorCode: 101; ErrorMsg: 'Max number of tickers has been reached.'),
    (TypeCode: mcTWSError; ErrorCode: 102; ErrorMsg: 'Duplicate ticker ID.'),
    (TypeCode: mcTWSError; ErrorCode: 103; ErrorMsg: 'Duplicate order ID.'),
    (TypeCode: mcTWSError; ErrorCode: 104; ErrorMsg: 'Can''t modify a filled order.'),
    (TypeCode: mcTWSError; ErrorCode: 105; ErrorMsg: 'Order being modified does not match original order.'),
    (TypeCode: mcTWSError; ErrorCode: 106; ErrorMsg: 'Can''t transmit order ID:'),
    (TypeCode: mcTWSError; ErrorCode: 107; ErrorMsg: 'Cannot transmit incomplete order.'),
    (TypeCode: mcTWSError; ErrorCode: 109; ErrorMsg: 'Price is out of the range defined by the Percentage setting at order defaults frame. The order will not be transmitted.'),
    (TypeCode: mcTWSError; ErrorCode: 110; ErrorMsg: 'The price does not conform to the minimum price variation for this contract.'),
    (TypeCode: mcTWSError; ErrorCode: 111; ErrorMsg: 'The TIF (Tif type) and the order type are incompatible.'),
    (TypeCode: mcTWSError; ErrorCode: 113; ErrorMsg: 'The Tif option should be set to DAY for MOC and LOC orders.'),
    (TypeCode: mcTWSError; ErrorCode: 114; ErrorMsg: 'Relative orders are valid for stocks only.'),
    (TypeCode: mcTWSError; ErrorCode: 115; ErrorMsg: 'Relative orders for US stocks can only be submitted to SMART, SMART_ECN, INSTINET, or PRIMEX.'),
    (TypeCode: mcTWSError; ErrorCode: 116; ErrorMsg: 'The order cannot be transmitted to a dead exchange.'),
    (TypeCode: mcTWSError; ErrorCode: 117; ErrorMsg: 'The block order size must be at least 50.'),
    (TypeCode: mcTWSError; ErrorCode: 118; ErrorMsg: 'VWAP orders must be routed through the VWAP exchange.'),
    (TypeCode: mcTWSError; ErrorCode: 119; ErrorMsg: 'Only VWAP orders may be placed on the VWAP exchange.'),
    (TypeCode: mcTWSError; ErrorCode: 120; ErrorMsg: 'It is too late to place a VWAP order for today.'),
    (TypeCode: mcTWSError; ErrorCode: 121; ErrorMsg: 'Invalid BD flag for the order. Check "Destination" and "BD" flag.'),
    (TypeCode: mcTWSError; ErrorCode: 122; ErrorMsg: 'No request tag has been found for order:'),
    (TypeCode: mcTWSError; ErrorCode: 123; ErrorMsg: 'No record is available for conid:'),
    (TypeCode: mcTWSError; ErrorCode: 124; ErrorMsg: 'No market rule is available for conid:'),
    (TypeCode: mcTWSError; ErrorCode: 125; ErrorMsg: 'Buy price must be the same as the best asking price.'),
    (TypeCode: mcTWSError; ErrorCode: 126; ErrorMsg: 'Sell price must be the same as the best bidding price.'),
    (TypeCode: mcTWSError; ErrorCode: 129; ErrorMsg: 'VWAP orders must be submitted at least three minutes before the start time.'),
    (TypeCode: mcTWSError; ErrorCode: 131; ErrorMsg: 'The sweep-to-fill flag and display size are only valid for US stocks routed through SMART, and will be ignored.'),
    (TypeCode: mcTWSError; ErrorCode: 132; ErrorMsg: 'This order cannot be transmitted without a clearing account.'),
    (TypeCode: mcTWSError; ErrorCode: 133; ErrorMsg: 'Submit new order failed.'),
    (TypeCode: mcTWSError; ErrorCode: 134; ErrorMsg: 'Modify order failed.'),
    (TypeCode: mcTWSError; ErrorCode: 135; ErrorMsg: 'Can''t find order with ID ='),
    (TypeCode: mcTWSError; ErrorCode: 136; ErrorMsg: 'This order cannot be cancelled.'),
    (TypeCode: mcTWSError; ErrorCode: 137; ErrorMsg: 'VWAP orders can only be cancelled up to three minutes before the start time.'),
    (TypeCode: mcTWSError; ErrorCode: 138; ErrorMsg: 'Could not parse ticker request:'),
    (TypeCode: mcTWSError; ErrorCode: 139; ErrorMsg: 'Parsing error:'),
    (TypeCode: mcTWSError; ErrorCode: 140; ErrorMsg: 'The size value should be an integer:'),
    (TypeCode: mcTWSError; ErrorCode: 141; ErrorMsg: 'The price value should be a double:'),
    (TypeCode: mcTWSError; ErrorCode: 142; ErrorMsg: 'Institutional customer account does not have account info'),
    (TypeCode: mcTWSError; ErrorCode: 143; ErrorMsg: 'Requested ID is not an integer number.'),
    (TypeCode: mcTWSError; ErrorCode: 144; ErrorMsg: 'Order size does not match total share allocation. To adjust the share allocation, right-click on the order and select â€œModify > Share Allocation.â€�'),
    (TypeCode: mcTWSError; ErrorCode: 145; ErrorMsg: 'Error in validating entry fields -'),
    (TypeCode: mcTWSError; ErrorCode: 146; ErrorMsg: 'Invalid trigger method.'),
    (TypeCode: mcTWSError; ErrorCode: 147; ErrorMsg: 'The conditional contract info is incomplete.'),
    (TypeCode: mcTWSError; ErrorCode: 148; ErrorMsg: 'A conditional order can only be submitted when the order type is set to limit or market.'),
    (TypeCode: mcTWSError; ErrorCode: 151; ErrorMsg: 'This order cannot be transmitted without a user name.'),
    (TypeCode: mcTWSError; ErrorCode: 152; ErrorMsg: 'The "hidden" order attribute may not be specified for this order.'),
    (TypeCode: mcTWSError; ErrorCode: 153; ErrorMsg: 'EFPs can only be limit orders.'),
    (TypeCode: mcTWSError; ErrorCode: 154; ErrorMsg: 'Orders cannot be transmitted for a halted security.'),
    (TypeCode: mcTWSError; ErrorCode: 155; ErrorMsg: 'A sizeOp order must have a user name and account.'),
    (TypeCode: mcTWSError; ErrorCode: 156; ErrorMsg: 'A SizeOp order must go to IBSX'),
    (TypeCode: mcTWSError; ErrorCode: 157; ErrorMsg: 'An order can be EITHER Iceberg or Discretionary. Please remove either the Discretionary amount or the Display size.'),
    (TypeCode: mcTWSError; ErrorCode: 158; ErrorMsg: 'You must specify an offset amount or a percent offset value.'),
    (TypeCode: mcTWSError; ErrorCode: 159; ErrorMsg: 'The percent offset value must be between 0% and 100%.'),
    (TypeCode: mcTWSError; ErrorCode: 160; ErrorMsg: 'The size value cannot be zero.'),
    (TypeCode: mcTWSError; ErrorCode: 161; ErrorMsg: 'Cancel attempted when order is not in a cancellable state. Order permId ='),
    (TypeCode: mcTWSError; ErrorCode: 162; ErrorMsg: 'Historical market data Service error message.'),
    (TypeCode: mcTWSError; ErrorCode: 163; ErrorMsg: 'The price specified would violate the percentage constraint specified in the default order settings.'),
    (TypeCode: mcTWSError; ErrorCode: 164; ErrorMsg: 'There is no market data to check price percent violations.'),
    (TypeCode: mcTWSError; ErrorCode: 165; ErrorMsg: 'Historical market Data Service query message.'),
    (TypeCode: mcTWSError; ErrorCode: 166; ErrorMsg: 'HMDS Expired Contract Violation.'),
    (TypeCode: mcTWSError; ErrorCode: 167; ErrorMsg: 'VWAP order time must be in the future.'),
    (TypeCode: mcTWSError; ErrorCode: 168; ErrorMsg: 'Discretionary amount does not conform to the minimum price variation for this contract.'),
    (TypeCode: mcTWSError; ErrorCode: 200; ErrorMsg: 'No security definition has been found for the request OR The contract description specified for <Symbol> is ambiguous'),
    (TypeCode: mcTWSError; ErrorCode: 201; ErrorMsg: 'Order rejected - Reason: An attempted order was rejected by the IB servers.'),
    (TypeCode: mcTWSError; ErrorCode: 202; ErrorMsg: 'Order cancelled - Reason: An active order on the IB server was cancelled. '),
    (TypeCode: mcTWSError; ErrorCode: 203; ErrorMsg: 'The security <security> is not available or allowed for this account.'),
    (TypeCode: mcTWSError; ErrorCode: 300; ErrorMsg: 'Can''t find EId with ticker Id:'),
    (TypeCode: mcTWSError; ErrorCode: 301; ErrorMsg: 'Invalid ticker action:'),
    (TypeCode: mcTWSError; ErrorCode: 302; ErrorMsg: 'Error parsing stop ticker string:'),
    (TypeCode: mcTWSError; ErrorCode: 303; ErrorMsg: 'Invalid action:'),
    (TypeCode: mcTWSError; ErrorCode: 304; ErrorMsg: 'Invalid account value action:'),
    (TypeCode: mcTWSError; ErrorCode: 305; ErrorMsg: 'Request parsing error, the request has been ignored.'),
    (TypeCode: mcTWSError; ErrorCode: 306; ErrorMsg: 'Error processing DDE request:'),
    (TypeCode: mcTWSError; ErrorCode: 307; ErrorMsg: 'Invalid request topic:'),
    (TypeCode: mcTWSError; ErrorCode: 308; ErrorMsg: 'Unable to create the API page in TWS as the maximum number of pages already exists.'),
    (TypeCode: mcTWSError; ErrorCode: 309; ErrorMsg: 'Max number (3) of market depth requests has been reached. Note: TWS currently limits users to a maximum of 3 distinct market depth requests...'),
    (TypeCode: mcTWSError; ErrorCode: 310; ErrorMsg: 'Can''t find the subscribed market depth with tickerId:'),
    (TypeCode: mcTWSError; ErrorCode: 311; ErrorMsg: 'The origin is invalid.'),
    (TypeCode: mcTWSError; ErrorCode: 312; ErrorMsg: 'The combo details are invalid.'),
    (TypeCode: mcTWSError; ErrorCode: 313; ErrorMsg: 'The combo details for leg <leg number> are invalid.'),
    (TypeCode: mcTWSError; ErrorCode: 314; ErrorMsg: 'Security type BAG requires combo leg details.'),
    (TypeCode: mcTWSError; ErrorCode: 315; ErrorMsg: 'Stock combo legs are restricted to SMART order routing.'),
    (TypeCode: mcTWSError; ErrorCode: 316; ErrorMsg: 'Market depth data has been HALTED. Please re-subscribe.'),
    (TypeCode: mcTWSError; ErrorCode: 317; ErrorMsg: 'Market depth data has been RESET. Please empty deep book contents before applying any new entries.'),
    (TypeCode: mcTWSError; ErrorCode: 319; ErrorMsg: 'Invalid log level <log level>'),
    (TypeCode: mcTWSError; ErrorCode: 320; ErrorMsg: 'Server error when reading an API client request.'),
    (TypeCode: mcTWSError; ErrorCode: 321; ErrorMsg: 'Server error when validating an API client request.'),
    (TypeCode: mcTWSError; ErrorCode: 322; ErrorMsg: 'Server error when processing an API client request. Duplicate ticker id'),
    (TypeCode: mcTWSError; ErrorCode: 323; ErrorMsg: 'Server error: cause - s'),
    (TypeCode: mcTWSError; ErrorCode: 324; ErrorMsg: 'Server error when reading a DDE client request (missing information).'),
    (TypeCode: mcTWSError; ErrorCode: 325; ErrorMsg: 'Discretionary orders are not supported for this combination of exchange and order type.'),
    (TypeCode: mcTWSError; ErrorCode: 326; ErrorMsg: 'Unable to connect as the client id is already in use. Retry with a unique client id.'),
    (TypeCode: mcTWSError; ErrorCode: 327; ErrorMsg: 'Only API connections with clientId set to 0 can set the auto bind TWS orders property.'),
    (TypeCode: mcTWSError; ErrorCode: 328; ErrorMsg: 'Trailing stop orders can be attached to limit or stop-limit orders only.'),
    (TypeCode: mcTWSError; ErrorCode: 329; ErrorMsg: 'Order modify failed. Cannot change to the new order type.'),
    (TypeCode: mcTWSError; ErrorCode: 330; ErrorMsg: 'Only FA or STL customers can request managed accounts list.'),
    (TypeCode: mcTWSError; ErrorCode: 331; ErrorMsg: 'Internal error. FA or STL does not have any managed accounts.'),
    (TypeCode: mcTWSError; ErrorCode: 332; ErrorMsg: 'The account ErrorCodes for the order profile are invalid.'),
    (TypeCode: mcTWSError; ErrorCode: 333; ErrorMsg: 'Invalid share allocation syntax.'),
    (TypeCode: mcTWSError; ErrorCode: 334; ErrorMsg: 'Invalid Good Till Date order'),
    (TypeCode: mcTWSError; ErrorCode: 335; ErrorMsg: 'Invalid delta: The delta must be between 0 and 100.'),
    (TypeCode: mcTWSError; ErrorCode: 336; ErrorMsg: 'The time or time zone is invalid. The correct format is hh:mm:ss xxx where xxx is an optionally specified time-zone. E.g.: 15:59:00 EST Note that there is a space between the time and the time zone. If no time zone is specified, local time is assumed.'),
    (TypeCode: mcTWSError; ErrorCode: 337; ErrorMsg: 'The date, time, or time-zone entered is invalid. The correct format is yyyymmdd hh:mm:ss xxx where yyyymmdd and xxx are optional. E.g.: 20031126 15:59:00 ESTNote that there is a space between the date and time, and between the time and time-zone.'),
    (TypeCode: mcTWSError; ErrorCode: 338; ErrorMsg: 'Good After Time orders are currently disabled on this exchange.'),
    (TypeCode: mcTWSError; ErrorCode: 339; ErrorMsg: 'Futures spread are no longer supported. Please use combos instead.'),
    (TypeCode: mcTWSError; ErrorCode: 340; ErrorMsg: 'Invalid improvement amount for box auction strategy.'),
    (TypeCode: mcTWSError; ErrorCode: 341; ErrorMsg: 'Invalid delta. Valid values are from 1 to 100. You can set the delta from the "Pegged to Stock" section of the Order Ticket Panel, or by selecting Page/Layout from the main menu and adding the Delta column.'),
    (TypeCode: mcTWSError; ErrorCode: 342; ErrorMsg: 'Pegged order is not supported on this exchange.'),
    (TypeCode: mcTWSError; ErrorCode: 343; ErrorMsg: 'The date, time, or time-zone entered is invalid. The correct format is yyyymmdd hh:mm:ss xxx'),
    (TypeCode: mcTWSError; ErrorCode: 344; ErrorMsg: 'The account logged into is not a financial advisor account.'),
    (TypeCode: mcTWSError; ErrorCode: 345; ErrorMsg: 'Generic combo is not supported for FA advisor account.'),
    (TypeCode: mcTWSError; ErrorCode: 346; ErrorMsg: 'Not an institutional account or an away clearing account.'),
    (TypeCode: mcTWSError; ErrorCode: 347; ErrorMsg: 'Short sale slot value must be 1 (broker holds shares) or 2 (delivered from elsewhere).'),
    (TypeCode: mcTWSError; ErrorCode: 348; ErrorMsg: 'Order not a short sale – type must be SSHORT to specify short sale slot.'),
    (TypeCode: mcTWSError; ErrorCode: 349; ErrorMsg: 'Generic combo does not support "Good After" attribute.'),
    (TypeCode: mcTWSError; ErrorCode: 350; ErrorMsg: 'Minimum quantity is not supported for best combo order.'),
    (TypeCode: mcTWSError; ErrorCode: 351; ErrorMsg: 'The "Regular Trading Hours only" flag is not valid for this order.'),
    (TypeCode: mcTWSError; ErrorCode: 352; ErrorMsg: 'Short sale slot value of 2 (delivered from elsewhere) requires location.'),
    (TypeCode: mcTWSError; ErrorCode: 353; ErrorMsg: 'Short sale slot value of 1 requires no location be specified.'),
    (TypeCode: mcTWSError; ErrorCode: 354; ErrorMsg: 'Not subscribed to requested market data.'),
    (TypeCode: mcTWSError; ErrorCode: 355; ErrorMsg: 'Order size does not conform to market rule.'),
    (TypeCode: mcTWSError; ErrorCode: 356; ErrorMsg: 'Smart-combo order does not support OCA group.'),
    (TypeCode: mcTWSError; ErrorCode: 357; ErrorMsg: 'Your client version is out of date.'),
    (TypeCode: mcTWSError; ErrorCode: 358; ErrorMsg: 'Smart combo child order not supported.'),
    (TypeCode: mcTWSError; ErrorCode: 359; ErrorMsg: 'Combo order only supports reduce on fill without block(OCA).'),
    (TypeCode: mcTWSError; ErrorCode: 360; ErrorMsg: 'No whatif check support for smart combo order.'),
    (TypeCode: mcTWSError; ErrorCode: 361; ErrorMsg: 'Invalid trigger price.'),
    (TypeCode: mcTWSError; ErrorCode: 362; ErrorMsg: 'Invalid adjusted stop price.'),
    (TypeCode: mcTWSError; ErrorCode: 363; ErrorMsg: 'Invalid adjusted stop limit price.'),
    (TypeCode: mcTWSError; ErrorCode: 364; ErrorMsg: 'Invalid adjusted trailing amount.'),
    (TypeCode: mcTWSError; ErrorCode: 365; ErrorMsg: 'No scanner subscription found for ticker id:'),
    (TypeCode: mcTWSError; ErrorCode: 366; ErrorMsg: 'No historical data query found for ticker id:'),
    (TypeCode: mcTWSError; ErrorCode: 367; ErrorMsg: 'Volatility type if set must be 1 or 2 for VOL orders. Do not set it for other order types.'),
    (TypeCode: mcTWSError; ErrorCode: 368; ErrorMsg: 'Reference Price Type must be 1 or 2 for dynamic volatility management. Do not set it for non-VOL orders.'),
    (TypeCode: mcTWSError; ErrorCode: 369; ErrorMsg: 'Volatility orders are only valid for US options.'),
    (TypeCode: mcTWSError; ErrorCode: 370; ErrorMsg: 'Dynamic Volatility orders must be SMART routed, or trade on a Price Improvement Exchange.'),
    (TypeCode: mcTWSError; ErrorCode: 371; ErrorMsg: 'VOL order requires positive floating point value for volatility. Do not set it for other order types.'),
    (TypeCode: mcTWSError; ErrorCode: 372; ErrorMsg: 'Cannot set dynamic VOL attribute on non-VOL order.'),
    (TypeCode: mcTWSError; ErrorCode: 373; ErrorMsg: 'Can only set stock range attribute on VOL or RELATIVE TO STOCK order.'),
    (TypeCode: mcTWSError; ErrorCode: 374; ErrorMsg: 'If both are set, the lower stock range attribute must be less than the upper stock range attribute.'),
    (TypeCode: mcTWSError; ErrorCode: 375; ErrorMsg: 'Stock range attributes cannot be negative.'),
    (TypeCode: mcTWSError; ErrorCode: 376; ErrorMsg: 'The order is not eligible for continuous update. The option must trade on a cheap-to-reroute exchange.'),
    (TypeCode: mcTWSError; ErrorCode: 377; ErrorMsg: 'Must specify valid delta hedge order aux. price.'),
    (TypeCode: mcTWSError; ErrorCode: 378; ErrorMsg: 'Delta hedge order type requires delta hedge aux. price to be specified.'),
    (TypeCode: mcTWSError; ErrorCode: 379; ErrorMsg: 'Delta hedge order type requires that no delta hedge aux. price be specified.'),
    (TypeCode: mcTWSError; ErrorCode: 380; ErrorMsg: 'This order type is not allowed for delta hedge orders.'),
    (TypeCode: mcTWSError; ErrorCode: 381; ErrorMsg: 'Your DDE.dll needs to be upgraded.'),
    (TypeCode: mcTWSError; ErrorCode: 382; ErrorMsg: 'The price specified violates the number of ticks constraint specified in the default order settings.'),
    (TypeCode: mcTWSError; ErrorCode: 383; ErrorMsg: 'The size specified violates the size constraint specified in the default order settings.'),
    (TypeCode: mcTWSError; ErrorCode: 384; ErrorMsg: 'Invalid DDE array request.'),
    (TypeCode: mcTWSError; ErrorCode: 385; ErrorMsg: 'Duplicate ticker ID for API scanner subscription.'),
    (TypeCode: mcTWSError; ErrorCode: 386; ErrorMsg: 'Duplicate ticker ID for API historical data query.'),
    (TypeCode: mcTWSError; ErrorCode: 387; ErrorMsg: 'Unsupported order type for this exchange and security type.'),
    (TypeCode: mcTWSError; ErrorCode: 388; ErrorMsg: 'Order size is smaller than the minimum requirement.'),
    (TypeCode: mcTWSError; ErrorCode: 389; ErrorMsg: 'Supplied routed order ID is not unique.'),
    (TypeCode: mcTWSError; ErrorCode: 390; ErrorMsg: 'Supplied routed order ID is invalid.'),
    (TypeCode: mcTWSError; ErrorCode: 391; ErrorMsg: 'The time or time-zone entered is invalid. The correct format is hh:mm:ss xxx'),
    (TypeCode: mcTWSError; ErrorCode: 392; ErrorMsg: 'Invalid order: contract expired.'),
    (TypeCode: mcTWSError; ErrorCode: 393; ErrorMsg: 'Short sale slot may be specified for delta hedge orders only.'),
    (TypeCode: mcTWSError; ErrorCode: 394; ErrorMsg: 'Invalid Process Time: must be integer number of milliseconds between 100 and 2000. Found:'),
    (TypeCode: mcTWSError; ErrorCode: 395; ErrorMsg: 'Due to system problems, orders with OCA groups are currently not being accepted.'),
    (TypeCode: mcTWSError; ErrorCode: 396; ErrorMsg: 'Due to system problems, application is currently accepting only Market and Limit orders for this contract.'),
    (TypeCode: mcTWSError; ErrorCode: 397; ErrorMsg: 'Due to system problems, application is currently accepting only Market and Limit orders for this contract.'),
    (TypeCode: mcTWSError; ErrorCode: 398; ErrorMsg: '< > cannot be used as a condition trigger.'),
    (TypeCode: mcTWSError; ErrorCode: 399; ErrorMsg: 'Order message error'),
    (TypeCode: mcTWSError; ErrorCode: 400; ErrorMsg: 'Algo order error.'),
    (TypeCode: mcTWSError; ErrorCode: 401; ErrorMsg: 'Length restriction.'),
    (TypeCode: mcTWSError; ErrorCode: 402; ErrorMsg: 'Conditions are not allowed for this contract.'),
    (TypeCode: mcTWSError; ErrorCode: 403; ErrorMsg: 'Invalid stop price.'),
    (TypeCode: mcTWSError; ErrorCode: 404; ErrorMsg: 'Shares for this order are not immediately available for short sale. The order will be held while we attempt to locate the shares.'),
    (TypeCode: mcTWSError; ErrorCode: 405; ErrorMsg: 'The child order quantity should be equivalent to the parent order size.'),
    (TypeCode: mcTWSError; ErrorCode: 406; ErrorMsg: 'The currency < > is not allowed.'),
    (TypeCode: mcTWSError; ErrorCode: 407; ErrorMsg: 'The symbol should contain valid non-uniErrorCode characters only.'),
    (TypeCode: mcTWSError; ErrorCode: 408; ErrorMsg: 'Invalid scale order increment.'),
    (TypeCode: mcTWSError; ErrorCode: 409; ErrorMsg: 'Invalid scale order. You must specify order component size.'),
    (TypeCode: mcTWSError; ErrorCode: 410; ErrorMsg: 'Invalid subsequent component size for scale order.'),
    (TypeCode: mcTWSError; ErrorCode: 411; ErrorMsg: 'The "Outside Regular Trading Hours" flag is not valid for this order.'),
    (TypeCode: mcTWSError; ErrorCode: 412; ErrorMsg: 'The contract is not available for trading.'),
    (TypeCode: mcTWSError; ErrorCode: 413; ErrorMsg: 'What-if order should have the transmit flag set to true.'),
    (TypeCode: mcTWSError; ErrorCode: 414; ErrorMsg: 'Snapshot market data subscription is not applicable to generic ticks.'),
    (TypeCode: mcTWSError; ErrorCode: 415; ErrorMsg: 'Wait until previous RFQ finishes and try again.'),
    (TypeCode: mcTWSError; ErrorCode: 416; ErrorMsg: 'RFQ is not applicable for the contract. Order ID:'),
    (TypeCode: mcTWSError; ErrorCode: 417; ErrorMsg: 'Invalid initial component size for scale order.'),
    (TypeCode: mcTWSError; ErrorCode: 418; ErrorMsg: 'Invalid scale order profit offset.'),
    (TypeCode: mcTWSError; ErrorCode: 419; ErrorMsg: 'Missing initial component size for scale order.'),
    (TypeCode: mcTWSError; ErrorCode: 420; ErrorMsg: 'Invalid real-time query.'),
    (TypeCode: mcTWSError; ErrorCode: 421; ErrorMsg: 'Invalid route.'),
    (TypeCode: mcTWSError; ErrorCode: 422; ErrorMsg: 'The account and clearing attributes on this order may not be changed.'),
    (TypeCode: mcTWSError; ErrorCode: 423; ErrorMsg: 'Cross order RFQ has been expired. THI committed size is no longer available. Please open order dialog and verify liquidity allocation.'),
    (TypeCode: mcTWSError; ErrorCode: 424; ErrorMsg: 'FA Order requires allocation to be specified.'),
    (TypeCode: mcTWSError; ErrorCode: 425; ErrorMsg: 'FA Order requires per-account manual allocations because there is no common clearing instruction. Please use order dialog Adviser tab to enter the allocation.'),
    (TypeCode: mcTWSError; ErrorCode: 426; ErrorMsg: 'None of the accounts have enough shares.'),
    (TypeCode: mcTWSError; ErrorCode: 427; ErrorMsg: 'Mutual Fund order requires monetary value to be specified.'),
    (TypeCode: mcTWSError; ErrorCode: 428; ErrorMsg: 'Mutual Fund Sell order requires shares to be specified.'),
    (TypeCode: mcTWSError; ErrorCode: 429; ErrorMsg: 'Delta neutral orders are only supported for combos (BAG security type).'),
    (TypeCode: mcTWSError; ErrorCode: 430; ErrorMsg: 'We are sorry, but fundamentals data for the security specified is not available.'),
    (TypeCode: mcTWSError; ErrorCode: 431; ErrorMsg: 'What to show field is missing or incorrect.'),
    (TypeCode: mcTWSError; ErrorCode: 432; ErrorMsg: 'Commission must not be negative.'),
    (TypeCode: mcTWSError; ErrorCode: 433; ErrorMsg: 'Invalid "Restore size after taking profit" for multiple account allocation scale order.'),
    (TypeCode: mcTWSError; ErrorCode: 434; ErrorMsg: 'The order size cannot be zero.'),
    (TypeCode: mcTWSError; ErrorCode: 435; ErrorMsg: 'You must specify an account.'),
    (TypeCode: mcTWSError; ErrorCode: 436; ErrorMsg: 'You must specify an allocation (either a single account, group, or profile).'),
    (TypeCode: mcTWSError; ErrorCode: 437; ErrorMsg: 'Order can have only one flag Outside RTH or Allow PreOpen.'),
    (TypeCode: mcTWSError; ErrorCode: 438; ErrorMsg: 'The application is now locked.'),
    (TypeCode: mcTWSError; ErrorCode: 439; ErrorMsg: 'Order processing failed. Algorithm definition not found.'),
    (TypeCode: mcTWSError; ErrorCode: 440; ErrorMsg: 'Order modify failed. Algorithm cannot be modified.'),
    (TypeCode: mcTWSError; ErrorCode: 441; ErrorMsg: 'Algo attributes validation failed:'),
    (TypeCode: mcTWSError; ErrorCode: 442; ErrorMsg: 'Specified algorithm is not allowed for this order.'),
    (TypeCode: mcTWSError; ErrorCode: 443; ErrorMsg: 'Order processing failed. Unknown algo attribute.'),
    (TypeCode: mcTWSError; ErrorCode: 444; ErrorMsg: 'Volatility Combo order is not yet acknowledged. Cannot submit changes at this time.'),
    (TypeCode: mcTWSError; ErrorCode: 445; ErrorMsg: 'The RFQ for this order is no longer valid.'),
    (TypeCode: mcTWSError; ErrorCode: 446; ErrorMsg: 'Missing scale order profit offset.'),
    (TypeCode: mcTWSError; ErrorCode: 447; ErrorMsg: 'Missing scale price adjustment amount or interval.'),
    (TypeCode: mcTWSError; ErrorCode: 448; ErrorMsg: 'Invalid scale price adjustment interval.'),
    (TypeCode: mcTWSError; ErrorCode: 449; ErrorMsg: 'Unexpected scale price adjustment amount or interval.'),
    (TypeCode: mcTWSError; ErrorCode: 507; ErrorMsg: 'Bad Message Length (Java-only)'),
    (TypeCode: mcTWSError; ErrorCode: 10000; ErrorMsg: 'Cross currency combo error.'),
    (TypeCode: mcTWSError; ErrorCode: 10001; ErrorMsg: 'Cross currency vol error.'),
    (TypeCode: mcTWSError; ErrorCode: 10002; ErrorMsg: 'Invalid non-guaranteed legs.'),
    (TypeCode: mcTWSError; ErrorCode: 10003; ErrorMsg: 'IBSX not allowed.'),
    (TypeCode: mcTWSError; ErrorCode: 10005; ErrorMsg: 'Read-only models.'),
    (TypeCode: mcTWSError; ErrorCode: 10006; ErrorMsg: 'Missing parent order.'),
    (TypeCode: mcTWSError; ErrorCode: 10007; ErrorMsg: 'Invalid hedge type.'),
    (TypeCode: mcTWSError; ErrorCode: 10008; ErrorMsg: 'Invalid beta value.'),
    (TypeCode: mcTWSError; ErrorCode: 10009; ErrorMsg: 'Invalid hedge ratio.'),
    (TypeCode: mcTWSError; ErrorCode: 10010; ErrorMsg: 'Invalid delta hedge order.'),
    (TypeCode: mcTWSError; ErrorCode: 10011; ErrorMsg: 'Currency is not supported for Smart combo.'),
    (TypeCode: mcTWSError; ErrorCode: 10012; ErrorMsg: 'Invalid allocation percentage'),
    (TypeCode: mcTWSError; ErrorCode: 10013; ErrorMsg: 'Smart routing API error (Smart routing opt-out required).'),
    (TypeCode: mcTWSError; ErrorCode: 10014; ErrorMsg: 'PctChange limits.'),
    (TypeCode: mcTWSError; ErrorCode: 10015; ErrorMsg: 'Trading is not allowed in the API.'),
    (TypeCode: mcTWSError; ErrorCode: 10016; ErrorMsg: 'Contract is not visible.'),
    (TypeCode: mcTWSError; ErrorCode: 10017; ErrorMsg: 'Contracts are not visible.'),
    (TypeCode: mcTWSError; ErrorCode: 10018; ErrorMsg: 'Orders use EV warning.'),
    (TypeCode: mcTWSError; ErrorCode: 10019; ErrorMsg: 'Trades use EV warning.'),
    (TypeCode: mcTWSError; ErrorCode: 10020; ErrorMsg: 'Display size should be smaller than order size./td>'),
    (TypeCode: mcTWSError; ErrorCode: 10021; ErrorMsg: 'Invalid leg2 to Mkt Offset API.'),
    (TypeCode: mcTWSError; ErrorCode: 10022; ErrorMsg: 'Invalid Leg Prio API.'),
    (TypeCode: mcTWSError; ErrorCode: 10023; ErrorMsg: 'Invalid combo display size API.'),
    (TypeCode: mcTWSError; ErrorCode: 10024; ErrorMsg: 'Invalid don''t start next legin API.'),
    (TypeCode: mcTWSError; ErrorCode: 10025; ErrorMsg: 'Invalid leg2 to Mkt time1 API.'),
    (TypeCode: mcTWSError; ErrorCode: 10026; ErrorMsg: 'Invalid leg2 to Mkt time2 API.'),
    (TypeCode: mcTWSError; ErrorCode: 10027; ErrorMsg: 'Invalid combo routing tag API.'),
    (TypeCode: mcTWSError; ErrorCode: 10090; ErrorMsg: 'Part of requested market data is not subscribed.'),
    (TypeCode: mcTWSError; ErrorCode: 10148; ErrorMsg: 'OrderId <OrderId> that needs to be cancelled can not be cancelled, state:'),
    (TypeCode: mcTWSError; ErrorCode: 10186; ErrorMsg: 'Requested market data is not subscribed. Delayed market data is not enabled'),
    (TypeCode: mcTWSError; ErrorCode: 10197; ErrorMsg: 'No market data during competing live session'),
    (TypeCode: mcTWSError; ErrorCode: 10225; ErrorMsg: 'No market data during competing session'),
    (TypeCode: mcTWSError; ErrorCode: 10230; ErrorMsg: 'You have unsaved FA changes. Please retry ''request FA'' operation later, when ''replace FA'' operation is complete'),
    (TypeCode: mcTWSError; ErrorCode: 10231; ErrorMsg: 'The following Groups and/or Profiles contain invalid accounts: <list of groups/profiles>'),
    (TypeCode: mcTWSError; ErrorCode: 10233; ErrorMsg: 'Defaults were inherited from CASH preset during the creation of this order.'),
    (TypeCode: mcTWSError; ErrorCode: 10234; ErrorMsg: 'The Decision Maker field is required and not set for this order (non-desktop).'),
    (TypeCode: mcTWSError; ErrorCode: 10235; ErrorMsg: 'The Decision Maker field is required and not set for this order (ibbot).'),
    (TypeCode: mcTWSError; ErrorCode: 10236; ErrorMsg: 'Child has to be AON if parent order is AON'),
    (TypeCode: mcTWSError; ErrorCode: 10237; ErrorMsg: 'All or None ticket can route entire unfilled size only'),
    (TypeCode: mcTWSError; ErrorCode: 10238; ErrorMsg: 'Some error occured during communication with Advisor Setup web-app'),
    (TypeCode: mcTWSError; ErrorCode: 10239; ErrorMsg: 'This order will affect one or more accounts that are flagged because they do not fit the required risk score criteria prescribed by the group/profile/model allocation.'),
    (TypeCode: mcTWSError; ErrorCode: 10240; ErrorMsg: 'You must enter a valid Price Cap.'),
    (TypeCode: mcTWSError; ErrorCode: 10241; ErrorMsg: 'Order Quantity is expressed in monetary terms. Modification is not supported via API. Please use desktop version to revise this order.'),
    (TypeCode: mcTWSError; ErrorCode: 10242; ErrorMsg: 'Fractional-sized order cannot be modified via API. Please use desktop version to revise this order.'),
    (TypeCode: mcTWSError; ErrorCode: 10243; ErrorMsg: 'Fractional-sized order cannot be placed via API. Please use desktop version to place this order.'),
    (TypeCode: mcTWSError; ErrorCode: 10244; ErrorMsg: 'Cash Quantity cannot be used for this order'),
    (TypeCode: mcTWSError; ErrorCode: 10245; ErrorMsg: 'This financial instrument does not support fractional shares trading'),
    (TypeCode: mcTWSError; ErrorCode: 10246; ErrorMsg: 'This order doesn''t support fractional shares trading'),
    (TypeCode: mcTWSError; ErrorCode: 10247; ErrorMsg: 'Only IB SmartRouting supports fractional shares'),
    (TypeCode: mcTWSError; ErrorCode: 10248; ErrorMsg: '<Account> doesn''t have permission to trade fractional shares'),
    (TypeCode: mcTWSError; ErrorCode: 10249; ErrorMsg: '<Order type>=""> order doesn''t support fractional shares'),
    (TypeCode: mcTWSError; ErrorCode: 10250; ErrorMsg: 'The size does not conform to the minimum variation of for this contract'),
    (TypeCode: mcTWSError; ErrorCode: 10251; ErrorMsg: 'Fractional shares are not supported for allocation orders'),
    (TypeCode: mcTWSError; ErrorCode: 10252; ErrorMsg: 'This non-close-position order doesn''t support fractional shares trading'),
    (TypeCode: mcTWSError; ErrorCode: 10253; ErrorMsg: 'Clear Away orders are not supported for multi-leg combo with attached hedge.'),
    (TypeCode: mcTWSError; ErrorCode: 10254; ErrorMsg: 'Invalid Order: bond expired'),
    (TypeCode: mcTWSError; ErrorCode: 10268; ErrorMsg: 'The ''EtradeOnly'' order attribute is not supported	The EtradeOnly IBApi.Order attribute is no longer supported. Error received with TWS versions 983+'),
    (TypeCode: mcTWSError; ErrorCode: 10269; ErrorMsg: 'The ''firmQuoteOnly'' order attribute is not supported	The firmQuoteOnly IBApi.Order attribute is no longer supported. Error received with TWS versions 983+'),
    (TypeCode: mcTWSError; ErrorCode: 10270; ErrorMsg: 'The ''nbboPriceCap'' order attribute is not supported	The nbboPriceCap IBApi.Order attribute is no longer supported. Error received with TWS versions 983+'),
    (TypeCode: mcTWSError; ErrorCode: 10276; ErrorMsg: 'News feed is not allowed	The API client is not permissioned for receiving WSH news feed.'),
    (TypeCode: mcTWSError; ErrorCode: 10277; ErrorMsg: 'News feed permissions required	The API client is not subscribed to receive WSH news feed'),
    (TypeCode: mcTWSError; ErrorCode: 10278; ErrorMsg: 'Duplicate WSH metadata request	A request is already pending for the same API client.'),
    (TypeCode: mcTWSError; ErrorCode: 10279; ErrorMsg: 'Failed request WSH metadata	A general error occurred when processing the request.'),
    (TypeCode: mcTWSError; ErrorCode: 10280; ErrorMsg: 'Failed cancel WSH metadata	A general error occurred when processing the request.'),
    (TypeCode: mcTWSError; ErrorCode: 10281; ErrorMsg: 'Duplicate WSH event data request	A request is already pending for the same API client.'),
    (TypeCode: mcTWSError; ErrorCode: 10282; ErrorMsg: 'WSH metadata not requested	WSH metadata was not requested by first sending a reqWshMetaData request.'),
    (TypeCode: mcTWSError; ErrorCode: 10283; ErrorMsg: 'Fail request WSH event data	A general error occurred when processing the request.'),
    (TypeCode: mcTWSError; ErrorCode: 10284; ErrorMsg: 'Fail cancel WSH event data. A general error occurred when processing the request.'),
    (TypeCode: mcUserError; ErrorCode: 20001; ErrorMsg: 'Symbol is empty'),
    (TypeCode: mcUserError; ErrorCode: 20002; ErrorMsg: 'Currency is empty'),
    (TypeCode: mcUserError; ErrorCode: 20003; ErrorMsg: 'Exchange is empty'),
    (TypeCode: mcUserError; ErrorCode: 20004; ErrorMsg: 'Expiry is over'),
    (TypeCode: mcUserError; ErrorCode: -1;    ErrorMsg: '')
  );

  function GetTWSMessageItem(aErrorCode: Integer): TTWSMessageItem;

implementation

function GetTWSMessageItem(aErrorCode: Integer): TTWSMessageItem;
begin
  Result := ArrayMessages[High(ArrayMessages)];
  for var TWSMessageItem in ArrayMessages do
    if (TWSMessageItem.ErrorCode = aErrorCode) then
      Exit(TWSMessageItem);
end;

end.
